# Generated by Django 2.1.1 on 2019-07-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190722_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_choice_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_choice_3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_choice_4',
            field=models.CharField(max_length=100),
        ),
    ]
