# Generated by Django 2.1.1 on 2019-07-29 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190722_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Course'),
            preserve_default=False,
        ),
    ]
