# Generated by Django 2.1.1 on 2019-08-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiztoken_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
