# Generated by Django 2.1.1 on 2019-08-19 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_quiztoken_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztoken',
            name='course',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='quiz.Course'),
        ),
    ]
